apiVersion: apps/v1
kind: Deployment
metadata:
  name: leukemia-segmentation-app
  labels:
    app: leukemia-segmentation-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leukemia-segmentation-app
  template:
    metadata:
      labels:
        app: leukemia-segmentation-app
    spec:
      containers:
      - name: leukemia-segmentation-app
        image: gayathri814/leukemia-segmentation-app:v42
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
